language: objective-c
osx_image: xcode7.2
xcode_project: xDripG5.xcodeproj
xcode_scheme: xDripG5
xcode_sdk: iphonesimulator9.2
env:
  global:
    - FRAMEWORK_NAME=xDripG5
before_install:
  - brew update
  - brew install carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current

# cache: cocoapods
# podfile: Example/Podfile

# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

# script:
# - set -o pipefail && xcodebuild test -workspace Example/xDripG5.xcworkspace -scheme xDripG5-Example -sdk iphonesimulator -destination name="iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint --allow-warnings
